server:
  port: 0 
spring:
  application:
    name: CurrencyConversionFactorService
  profiles:
    active: dev
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
            
      
      
  